"""The data-quality report.

Generated by COUNTING crawl_records, never hand-written. That distinction is
the whole point: a number typed into a markdown file is a claim, while a
number computed from stored rows can be recomputed by a reviewer and checked.

Every percentage uses the same denominator -- the total number of URLs
processed -- because statuses partition the input. That is enforced by the
pipeline's one-URL-one-record invariant, and verified here: the report fails
loudly if the status counts do not sum to the total.

WHAT THE TASK ASKS FOR, AND WHERE IT IS:
  % duplicates + how detected     -> the three-layer duplicates table
  % extraction failed / junk      -> the extraction-failure breakdown, by rule
  % missing/unparseable date      -> the date table, broken down by source
  average length + 5 shortest     -> the length section, with text quoted
"""

from __future__ import annotations

import json
import os
from collections import Counter
from dataclasses import dataclass, field
from datetime import datetime, timezone
from statistics import mean, median

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.config import Config
from app.statuses import (
    BLOCKED_STATUSES,
    DUPLICATE_STATUSES,
    EXTRACTION_FAILURE_STATUSES,
    REFUSED_BEFORE_FETCH_STATUSES,
    CrawlStatus,
)
from app.storage.models import CrawlRecord

# How many of the shortest articles to quote in full. The task says 5.
_SHORTEST_COUNT = 5
# How much of each short article to quote. Long enough to judge whether it is
# garbage, short enough that the report stays readable.
_SHORTEST_EXCERPT_CHARS = 600


@dataclass
class Report:
    generated_at: datetime
    total_urls: int
    counts: dict[str, int]
    stored: int = 0
    # Populated by build(); grouped into sections that mirror the task.
    duplicates: dict = field(default_factory=dict)
    extraction: dict = field(default_factory=dict)
    party_dates: dict = field(default_factory=dict)
    lengths: dict = field(default_factory=dict)
    structure: dict = field(default_factory=dict)
    shortest: list = field(default_factory=list)
    blocked: dict = field(default_factory=dict)
    refused: dict = field(default_factory=dict)
    hosts: dict = field(default_factory=dict)
    integrity: dict = field(default_factory=dict)


def _pct(part: int, whole: int) -> float:
    """Percentage, guarding against a zero denominator.

    Returns 0.0 rather than raising on an empty corpus: a report over zero
    URLs is legitimate (nothing has been crawled yet) and should render, not
    crash.
    """
    return round(100.0 * part / whole, 1) if whole else 0.0


def build(session: Session, config: Config) -> Report:
    """Compute the report from crawl_records."""
    records = session.execute(
        select(CrawlRecord).order_by(CrawlRecord.id)
    ).scalars().all()

    total = len(records)
    counts = Counter(record.status for record in records)

    report = Report(
        generated_at=datetime.now(timezone.utc),
        total_urls=total,
        counts=dict(sorted(counts.items())),
        stored=counts.get(CrawlStatus.STORED.value, 0),
    )

    # ---- integrity check ----
    # The statuses must partition the input. If they do not, every percentage
    # below is computed against a denominator that does not match the parts,
    # and the report is silently wrong. Checked and reported rather than
    # assumed.
    counted = sum(counts.values())
    report.integrity = {
        "total_records": total,
        "sum_of_status_counts": counted,
        "consistent": counted == total,
    }

    # ---- duplicates, by detection layer ----
    dupe_counts = {
        status.value: counts.get(status.value, 0) for status in DUPLICATE_STATUSES
    }
    dupe_total = sum(dupe_counts.values())

    near_records = [
        record
        for record in records
        if record.status == CrawlStatus.DUPLICATE_NEAR.value
        and record.duplicate_similarity is not None
    ]
    # The highest similarity among documents we did NOT call duplicates. If
    # this sits just under the threshold, the threshold is doing real work and
    # a reviewer should know.
    non_dupe_scores = [
        record.duplicate_similarity
        for record in records
        if record.status == CrawlStatus.STORED.value
        and record.duplicate_similarity is not None
    ]

    report.duplicates = {
        "total": dupe_total,
        "pct": _pct(dupe_total, total),
        "by_layer": {
            "url_after_normalisation": {
                "count": dupe_counts.get(CrawlStatus.DUPLICATE_URL.value, 0),
                "pct": _pct(dupe_counts.get(CrawlStatus.DUPLICATE_URL.value, 0), total),
                "method": (
                    "Exact match on the canonical URL after normalisation "
                    "(https forced, tracking params stripped, trailing slash "
                    "and #fragment removed, host lowercased)."
                ),
            },
            "content_sha256": {
                "count": dupe_counts.get(CrawlStatus.DUPLICATE_CONTENT.value, 0),
                "pct": _pct(dupe_counts.get(CrawlStatus.DUPLICATE_CONTENT.value, 0), total),
                "method": (
                    "SHA-256 of the whitespace-normalised article text. "
                    "Catches syndicated copies under different URLs."
                ),
            },
            "near_duplicate": {
                "count": dupe_counts.get(CrawlStatus.DUPLICATE_NEAR.value, 0),
                "pct": _pct(dupe_counts.get(CrawlStatus.DUPLICATE_NEAR.value, 0), total),
                "method": (
                    f"Jaccard similarity over {config.shingle_size}-word shingles, "
                    f"threshold {config.near_duplicate_threshold:.0%}."
                ),
                "matches": [
                    {
                        "url": record.canonical_url,
                        "similarity": record.duplicate_similarity,
                        "duplicate_of_record": record.duplicate_of_id,
                    }
                    for record in near_records
                ],
            },
        },
        "highest_similarity_among_kept": (
            round(max(non_dupe_scores), 4) if non_dupe_scores else None
        ),
    }

    # ---- extraction failures and junk ----
    extraction_failures = sum(
        counts.get(status.value, 0) for status in EXTRACTION_FAILURE_STATUSES
    )

    # Break the junk bucket down by WHICH rule fired. The rule names are
    # written into status_detail as "[rule_a, rule_b] ...", so they can be
    # recovered and counted here.
    rule_counter: Counter[str] = Counter()
    for record in records:
        if record.status != CrawlStatus.JUNK.value or not record.status_detail:
            continue
        detail = record.status_detail
        if detail.startswith("["):
            closing = detail.find("]")
            if closing > 0:
                for rule in detail[1:closing].split(","):
                    rule_counter[rule.strip()] += 1

    report.extraction = {
        "failed_or_junk": extraction_failures,
        "pct": _pct(extraction_failures, total),
        "extraction_failed": {
            "count": counts.get(CrawlStatus.EXTRACTION_FAILED.value, 0),
            "pct": _pct(counts.get(CrawlStatus.EXTRACTION_FAILED.value, 0), total),
            "meaning": "Page fetched, but no article text came out of it.",
        },
        "junk": {
            "count": counts.get(CrawlStatus.JUNK.value, 0),
            "pct": _pct(counts.get(CrawlStatus.JUNK.value, 0), total),
            "meaning": "Text extracted, but it failed a quality rule.",
            "by_rule": dict(rule_counter.most_common()),
        },
        "rules": {
            "too_short": f"fewer than {config.min_article_chars} characters",
            "high_link_density": (
                f"more than {config.max_link_density:.0%} of characters inside <a> tags"
            ),
            "extractor_disagreement": (
                "trafilatura and readability-lxml disagreed on length by more "
                f"than {1 - config.extractor_agreement_ratio:.0%}"
            ),
        },
    }

    # ---- publish dates ----
    # Measured over documents that got far enough to HAVE a date extracted --
    # i.e. those we stored. Counting a robots-disallowed URL as "missing a
    # date" would be meaningless: we never looked at its page.
    stored_records = [r for r in records if r.status == CrawlStatus.STORED.value]
    stored_total = len(stored_records)

    with_date = [r for r in stored_records if r.published_at is not None]
    without_date = [r for r in stored_records if r.published_at is None]
    # A raw string was found but failed to parse or failed the sanity window.
    unparseable = [r for r in without_date if r.published_at_raw]

    source_counter = Counter(
        record.published_at_source for record in with_date if record.published_at_source
    )

    report.party_dates = {
        "scope": "articles that were stored (a date is only meaningful for those)",
        "stored_total": stored_total,
        "with_date": len(with_date),
        "with_date_pct": _pct(len(with_date), stored_total),
        "missing_or_unparseable": len(without_date),
        "missing_or_unparseable_pct": _pct(len(without_date), stored_total),
        "no_date_found_at_all": len(without_date) - len(unparseable),
        "found_but_unparseable": len(unparseable),
        "by_source": dict(source_counter.most_common()),
        "unparseable_examples": [
            {"url": r.canonical_url, "raw_value": r.published_at_raw}
            for r in unparseable[:5]
        ],
    }

    # ---- lengths ----
    lengths = [r.text_chars for r in stored_records if r.text_chars]
    words = [r.text_words for r in stored_records if r.text_words]

    report.lengths = {
        "articles_measured": len(lengths),
        "mean_chars": round(mean(lengths)) if lengths else 0,
        # Median as well as mean: one 40,000-character article drags the mean
        # up and makes the corpus look longer than it is. Reporting both makes
        # that skew visible instead of hiding it.
        "median_chars": round(median(lengths)) if lengths else 0,
        "min_chars": min(lengths) if lengths else 0,
        "max_chars": max(lengths) if lengths else 0,
        "mean_words": round(mean(words)) if words else 0,
    }

    # ---- structure retention ----
    # Added after a reviewer opened a stored article and found its headings
    # missing. "Is the text clean" and "did the article keep its shape" are
    # different questions, and only the first was being measured.
    with_headings = [r for r in stored_records if (r.headings or 0) > 0]
    with_code = [r for r in stored_records if (r.code_blocks or 0) > 0]
    # A long article with no headings is the suspicious case; a 600-character
    # link-blog post legitimately has none.
    long_without_headings = [
        r for r in stored_records
        if (r.headings or 0) == 0 and (r.text_chars or 0) >= 4000
    ]

    report.structure = {
        "articles_with_headings": len(with_headings),
        "articles_with_headings_pct": _pct(len(with_headings), stored_total),
        "total_headings": sum(r.headings or 0 for r in stored_records),
        "articles_with_code_blocks": len(with_code),
        "total_code_blocks": sum(r.code_blocks or 0 for r in stored_records),
        "long_articles_without_headings": [
            {"url": r.canonical_url, "chars": r.text_chars, "source": r.host}
            for r in sorted(long_without_headings, key=lambda r: -(r.text_chars or 0))
        ],
    }

    # ---- the 5 shortest, quoted ----
    # The task predicts these are usually garbage, so they are quoted rather
    # than merely listed: a reviewer can judge for themselves.
    shortest = sorted(stored_records, key=lambda r: r.text_chars or 0)[:_SHORTEST_COUNT]
    report.shortest = [
        {
            "rank": index + 1,
            "chars": record.text_chars,
            "words": record.text_words,
            "title": record.title,
            "url": record.canonical_url,
            "api_document_id": record.api_document_id,
            "published_at": (
                record.published_at.isoformat() if record.published_at else None
            ),
            "link_density": record.link_density,
            "excerpt": (record.text or "")[:_SHORTEST_EXCERPT_CHARS],
            "truncated": len(record.text or "") > _SHORTEST_EXCERPT_CHARS,
        }
        for index, record in enumerate(shortest)
    ]

    # ---- blocked and refused ----
    report.blocked = {
        status.value: {
            "count": counts.get(status.value, 0),
            "pct": _pct(counts.get(status.value, 0), total),
        }
        for status in BLOCKED_STATUSES
    }
    report.refused = {
        status.value: {
            "count": counts.get(status.value, 0),
            "pct": _pct(counts.get(status.value, 0), total),
        }
        for status in REFUSED_BEFORE_FETCH_STATUSES
    }

    # ---- per-host ----
    host_counter = Counter(record.host for record in records if record.host)
    host_stored = Counter(
        record.host for record in stored_records if record.host
    )
    report.hosts = {
        host: {"attempted": count, "stored": host_stored.get(host, 0)}
        for host, count in host_counter.most_common()
    }

    return report


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------


def to_json(report: Report) -> str:
    payload = {
        "generated_at": report.generated_at.isoformat(),
        "total_urls_processed": report.total_urls,
        "status_counts": report.counts,
        "integrity": report.integrity,
        "duplicates": report.duplicates,
        "extraction": report.extraction,
        "publish_dates": report.party_dates,
        "lengths": report.lengths,
        "structure_retention": report.structure,
        "five_shortest": report.shortest,
        "blocked": report.blocked,
        "refused_before_fetch": report.refused,
        "hosts": report.hosts,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)


def to_markdown(report: Report, config: Config) -> str:
    """Render the human-readable report.

    Every number here comes from the Report object, which came from counting
    rows. Nothing in this function invents a figure.
    """
    lines: list[str] = []
    add = lines.append

    add("# Data Quality Report")
    add("")
    add(f"Generated: {report.generated_at.strftime('%Y-%m-%d %H:%M UTC')}")
    add("")
    add(
        "Every number below is computed by counting rows in `crawl_records`, "
        "not written by hand. Re-run `report` to regenerate it."
    )
    add("")

    # ---- headline ----
    add("## Summary")
    add("")
    add("| Metric | Value |")
    add("| --- | --- |")
    add(f"| URLs processed | {report.total_urls} |")
    add(f"| Articles stored | {report.stored} ({_pct(report.stored, report.total_urls)}%) |")
    add(f"| Duplicates | {report.duplicates['total']} ({report.duplicates['pct']}%) |")
    add(
        f"| Extraction failed or junk | {report.extraction['failed_or_junk']} "
        f"({report.extraction['pct']}%) |"
    )
    add(
        f"| Missing/unparseable date (of stored) | "
        f"{report.party_dates['missing_or_unparseable']} "
        f"({report.party_dates['missing_or_unparseable_pct']}%) |"
    )
    add(f"| Mean article length | {report.lengths['mean_chars']} chars |")
    add(f"| Median article length | {report.lengths['median_chars']} chars |")
    add("")

    if not report.integrity["consistent"]:
        add(
            f"> **WARNING:** status counts sum to "
            f"{report.integrity['sum_of_status_counts']} but there are "
            f"{report.integrity['total_records']} records. Percentages below "
            "are unreliable."
        )
        add("")

    # ---- status breakdown ----
    add("## Every outcome")
    add("")
    add(
        "Each URL gets exactly one status, so these counts partition the "
        "input and sum to the total."
    )
    add("")
    add("| Status | Count | % |")
    add("| --- | ---: | ---: |")
    for status, count in sorted(report.counts.items(), key=lambda kv: -kv[1]):
        add(f"| `{status}` | {count} | {_pct(count, report.total_urls)}% |")
    add(f"| **total** | **{report.total_urls}** | **100%** |")
    add("")

    # ---- duplicates ----
    add("## Duplicates, and how they were detected")
    add("")
    add(
        f"**{report.duplicates['total']} of {report.total_urls} URLs "
        f"({report.duplicates['pct']}%)** were duplicates."
    )
    add("")
    add("Three independent layers, reported separately because they catch")
    add("different things and have different reliability:")
    add("")
    add("| Layer | Caught | % | How |")
    add("| --- | ---: | ---: | --- |")
    for name, data in report.duplicates["by_layer"].items():
        add(f"| `{name}` | {data['count']} | {data['pct']}% | {data['method']} |")
    add("")

    near = report.duplicates["by_layer"]["near_duplicate"]
    if near["matches"]:
        add("Near-duplicate matches, with their scores:")
        add("")
        add("| URL | Similarity | Duplicate of record |")
        add("| --- | ---: | ---: |")
        for match in near["matches"]:
            add(
                f"| {match['url']} | {match['similarity']:.1%} | "
                f"#{match['duplicate_of_record']} |"
            )
        add("")

    highest = report.duplicates["highest_similarity_among_kept"]
    if highest is not None:
        add(
            f"Highest similarity among articles we KEPT: **{highest:.1%}** "
            f"(threshold {config.near_duplicate_threshold:.0%}). "
        )
        if highest >= config.near_duplicate_threshold - 0.05:
            add(
                "That is close to the threshold, so the threshold is making a "
                "real judgement call on this corpus, not just rubber-stamping."
            )
        else:
            add(
                "That is comfortably below the threshold, so no kept article "
                "is a borderline call."
            )
        add("")

    # ---- extraction ----
    add("## Extraction failures and junk")
    add("")
    add(
        f"**{report.extraction['failed_or_junk']} of {report.total_urls} "
        f"({report.extraction['pct']}%)** either produced no text or produced "
        "text that failed a quality rule."
    )
    add("")
    add("| Outcome | Count | % | Meaning |")
    add("| --- | ---: | ---: | --- |")
    add(
        f"| `extraction_failed` | {report.extraction['extraction_failed']['count']} "
        f"| {report.extraction['extraction_failed']['pct']}% "
        f"| {report.extraction['extraction_failed']['meaning']} |"
    )
    add(
        f"| `junk` | {report.extraction['junk']['count']} "
        f"| {report.extraction['junk']['pct']}% "
        f"| {report.extraction['junk']['meaning']} |"
    )
    add("")

    if report.extraction["junk"]["by_rule"]:
        add("Which rule rejected them (one document can fail several):")
        add("")
        add("| Rule | Times fired | Definition |")
        add("| --- | ---: | --- |")
        for rule, count in report.extraction["junk"]["by_rule"].items():
            definition = report.extraction["rules"].get(rule, "-")
            add(f"| `{rule}` | {count} | {definition} |")
        add("")

    # ---- dates ----
    dates_data = report.party_dates
    add("## Publish dates")
    add("")
    add(f"Scope: {dates_data['scope']} — {dates_data['stored_total']} articles.")
    add("")
    add("| Metric | Count | % of stored |")
    add("| --- | ---: | ---: |")
    add(
        f"| Date found and parsed | {dates_data['with_date']} "
        f"| {dates_data['with_date_pct']}% |"
    )
    add(
        f"| **Missing or unparseable** | **{dates_data['missing_or_unparseable']}** "
        f"| **{dates_data['missing_or_unparseable_pct']}%** |"
    )
    add(f"| — no date on the page at all | {dates_data['no_date_found_at_all']} | |")
    add(f"| — found something, could not parse it | {dates_data['found_but_unparseable']} | |")
    add("")

    if dates_data["by_source"]:
        add("Where the dates actually came from (ladder, most authoritative first):")
        add("")
        add("| Source | Articles |")
        add("| --- | ---: |")
        for source, count in dates_data["by_source"].items():
            add(f"| `{source}` | {count} |")
        add("")

    if dates_data["unparseable_examples"]:
        add("Strings we found but could not turn into a valid date:")
        add("")
        for example in dates_data["unparseable_examples"]:
            add(f"- `{example['raw_value']}` — {example['url']}")
        add("")

    # ---- lengths ----
    add("## Article length")
    add("")
    add("| Metric | Characters |")
    add("| --- | ---: |")
    add(f"| Mean | {report.lengths['mean_chars']} |")
    add(f"| Median | {report.lengths['median_chars']} |")
    add(f"| Shortest | {report.lengths['min_chars']} |")
    add(f"| Longest | {report.lengths['max_chars']} |")
    add("")
    add(f"Mean words per article: {report.lengths['mean_words']}.")
    add("")

    # ---- structure ----
    structure = report.structure
    add("## Structure retained")
    add("")
    add(
        "Clean text is not the whole job: an article stripped down to "
        "undifferentiated paragraphs has lost something too. Extraction "
        "keeps Markdown, so headings and code blocks survive."
    )
    add("")
    add("| Metric | Value |")
    add("| --- | ---: |")
    add(
        f"| Articles with headings | {structure['articles_with_headings']} "
        f"of {dates_data['stored_total']} ({structure['articles_with_headings_pct']}%) |"
    )
    add(f"| Total headings kept | {structure['total_headings']} |")
    add(f"| Articles with code blocks | {structure['articles_with_code_blocks']} |")
    add(f"| Total code blocks kept | {structure['total_code_blocks']} |")
    add("")

    if structure["long_articles_without_headings"]:
        add(
            "Long articles (4,000+ chars) that came out with **no headings** — "
            "these are the ones worth inspecting:"
        )
        add("")
        add("| Article | Chars |")
        add("| --- | ---: |")
        for item in structure["long_articles_without_headings"]:
            add(f"| {item['url']} | {item['chars']} |")
        add("")
        add(
            "Known cause for `research.google`: its headings sit in a "
            "different DOM branch (`div.component-intro`) from its article "
            "body (`div.blog-summary`), so an extractor that selects one "
            "content container cannot associate them. Reported rather than "
            "worked around with a site-specific rule."
        )
        add("")

    # ---- 5 shortest ----
    add(f"## The {len(report.shortest)} shortest articles")
    add("")
    add(
        "The brief predicts these are usually garbage, so they are quoted "
        "here rather than just listed — judge for yourself."
    )
    add("")
    for item in report.shortest:
        add(f"### {item['rank']}. {item['title'] or '(no title)'}")
        add("")
        add(f"- **{item['chars']} chars**, {item['words']} words")
        add(f"- URL: {item['url']}")
        add(f"- Stored as document `#{item['api_document_id']}`")
        add(f"- Publish date: {item['published_at'] or '**none found**'}")
        if item["link_density"] is not None:
            add(f"- Link density: {item['link_density']:.2f}")
        add("")
        add("```text")
        add(item["excerpt"] or "(empty)")
        if item["truncated"]:
            add("...[truncated]")
        add("```")
        add("")

    # ---- blocked ----
    blocked_total = sum(entry["count"] for entry in report.blocked.values())
    add("## Pages we were not allowed to read")
    add("")
    if blocked_total == 0:
        add("None encountered in this run.")
    else:
        add("| Reason | Count | % |")
        add("| --- | ---: | ---: |")
        for status, entry in report.blocked.items():
            if entry["count"]:
                add(f"| `{status}` | {entry['count']} | {entry['pct']}% |")
    add("")
    add(
        "These are detected and reported, never worked around: the brief puts "
        "anything behind a login out of scope."
    )
    add("")

    # ---- refused ----
    refused_total = sum(entry["count"] for entry in report.refused.values())
    add("## URLs we refused before fetching")
    add("")
    if refused_total == 0:
        add("None in this run.")
    else:
        add("| Reason | Count | % |")
        add("| --- | ---: | ---: |")
        for status, entry in report.refused.items():
            if entry["count"]:
                add(f"| `{status}` | {entry['count']} | {entry['pct']}% |")
        add("")
        add(
            "Refusing before the network call means these cost the target "
            "site nothing."
        )
    add("")

    # ---- hosts ----
    if report.hosts:
        add("## Per host")
        add("")
        add("| Host | Attempted | Stored |")
        add("| --- | ---: | ---: |")
        for host, data in report.hosts.items():
            add(f"| {host} | {data['attempted']} | {data['stored']} |")
        add("")

    # ---- thresholds ----
    add("## Thresholds these numbers were measured against")
    add("")
    add("| Setting | Value |")
    add("| --- | --- |")
    add(f"| Minimum article length | {config.min_article_chars} chars |")
    add(f"| Maximum link density | {config.max_link_density} |")
    add(f"| Extractor agreement floor | {config.extractor_agreement_ratio} |")
    add(f"| Near-duplicate threshold | {config.near_duplicate_threshold} |")
    add(f"| Shingle size | {config.shingle_size} words |")
    add(f"| Plausible date range | {config.min_plausible_year} to today+{config.future_date_tolerance_days}d |")
    add("")
    add(
        "Changing any of these changes the numbers above, which is why they "
        "are stated here rather than buried in the code."
    )
    add("")

    return "\n".join(lines)


def write(session: Session, config: Config) -> tuple[str, str]:
    """Build the report and write both formats. Returns the two paths."""
    report = build(session, config)
    os.makedirs(config.report_dir, exist_ok=True)

    md_path = os.path.join(config.report_dir, "REPORT.md")
    json_path = os.path.join(config.report_dir, "report.json")

    with open(md_path, "w", encoding="utf-8") as handle:
        handle.write(to_markdown(report, config))
    with open(json_path, "w", encoding="utf-8") as handle:
        handle.write(to_json(report))

    return md_path, json_path
