"""The crawler's own tables.

These are SEPARATE from Day 1's `documents` table and live in their own
database. The split is deliberate:

  documents (Day 1)   the clean, public output. Owned by the API.
  crawl_records       one row per URL we processed, including every failure.
  request_log         one row per HTTP request, for rate limiting.

Keeping the crawler's bookkeeping out of `documents` means the API's table
stays exactly what it claims to be -- stored articles -- and is not polluted
with rows for pages that were paywalled, junk or duplicates. It also means
the crawler can be reset and re-run without touching stored documents.

The report is generated by counting crawl_records, which is why every URL
gets a row here even when nothing was stored: percentages need a denominator
that includes the failures.
"""

from datetime import datetime, timezone

from sqlalchemy import (
    DateTime,
    Float,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


def _utcnow() -> datetime:
    """Timezone-aware UTC now.

    datetime.utcnow() is deprecated and returns a NAIVE datetime, which then
    compares wrongly against the aware values in these columns. Being
    explicit avoids the class of bug where a rate-limit window is off by the
    local timezone offset.
    """
    return datetime.now(timezone.utc)


class CrawlRecord(Base):
    """One row per URL the pipeline processed, whatever the outcome.

    This is the table the data-quality report is computed from.
    """

    __tablename__ = "crawl_records"

    # The canonical URL is the natural key: the whole point of normalisation
    # is that one article has one canonical form. A unique constraint here is
    # the DB-level enforcement of the URL-duplicate rule -- the same pattern
    # as Day 1's uq_documents_url, and for the same reason: the database is
    # the arbiter, so two concurrent crawls of one URL cannot both insert.
    __table_args__ = (
        UniqueConstraint("canonical_url", name="uq_crawl_records_canonical_url"),
        # The report groups by status constantly; the UI filters by it.
        Index("ix_crawl_records_status", "status"),
        # Content-hash lookup is how exact-duplicate detection works, so it
        # must be indexed or dedupe degrades to a table scan per article.
        Index("ix_crawl_records_content_hash", "content_hash"),
        Index("ix_crawl_records_host", "host"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    # ---------- identity ----------
    canonical_url: Mapped[str] = mapped_column(String(2000), nullable=False)
    # What the user actually typed, kept verbatim. When someone asks "why did
    # my URL end up somewhere else", this plus `repairs` is the answer.
    input_url: Mapped[str] = mapped_column(String(2000), nullable=False)
    host: Mapped[str] = mapped_column(String(255), nullable=False)
    # Semicolon-joined list of repairs applied during normalisation.
    repairs: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ---------- outcome ----------
    # Stored as the CrawlStatus enum's string value. Kept as a plain String
    # rather than a Postgres ENUM type: adding a status would otherwise need
    # a migration with ALTER TYPE, and the set of statuses is expected to
    # grow as new blocking patterns are found.
    status: Mapped[str] = mapped_column(String(40), nullable=False)
    # The specific cause: which junk rule fired, which HTTP code came back.
    # This is what lets "% junk" be broken down instead of being opaque.
    status_detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    http_status: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # ---------- extracted content ----------
    title: Mapped[str | None] = mapped_column(String(1000), nullable=True)
    # The cleaned article text. Kept here as well as in the Day 1 API so the
    # report can quote the 5 shortest articles without N API round-trips, and
    # so a failed push can be retried without re-crawling.
    text: Mapped[str | None] = mapped_column(Text, nullable=True)
    text_chars: Mapped[int | None] = mapped_column(Integer, nullable=True)
    text_words: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # SHA-256 of the normalised text: the exact-duplicate key.
    content_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # Structure retained by extraction. Recorded because "is the text clean"
    # and "did the article keep its shape" are different questions, and the
    # second was invisible until a reviewer opened a stored article and found
    # the headings gone. A long article with zero headings is worth flagging.
    headings: Mapped[int | None] = mapped_column(Integer, nullable=True)
    code_blocks: Mapped[int | None] = mapped_column(Integer, nullable=True)
    list_items: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # ---------- publish date ----------
    published_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    # WHICH extraction strategy produced the date: "rss", "json_ld",
    # "meta_article", "time_element", "text_pattern", or None.
    # This turns "% missing date" into a table showing where dates actually
    # come from, which is far more useful than a single percentage.
    published_at_source: Mapped[str | None] = mapped_column(String(40), nullable=True)
    # The unparsed string we found, kept even when parsing failed -- it is
    # the evidence for "unparseable" and shows what a new parser must handle.
    published_at_raw: Mapped[str | None] = mapped_column(String(200), nullable=True)

    # ---------- quality signals ----------
    # Characters inside <a> divided by total characters.
    link_density: Mapped[float | None] = mapped_column(Float, nullable=True)
    # Length from the SECOND extractor. Storing both lets the report show the
    # cross-check that produced the junk verdict, rather than asserting it.
    secondary_text_chars: Mapped[int | None] = mapped_column(Integer, nullable=True)
    extractor_agreement: Mapped[float | None] = mapped_column(Float, nullable=True)

    # ---------- provenance ----------
    # Path to the cached raw HTML, so any stored article can be traced back
    # to the exact bytes it was extracted from. This is what makes the
    # extraction re-runnable and the numbers reproducible.
    raw_html_path: Mapped[str | None] = mapped_column(String(500), nullable=True)
    # For duplicates: which crawl_record this one duplicates.
    duplicate_of_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Similarity score for near-duplicates, so the threshold decision is
    # visible rather than hidden.
    duplicate_similarity: Mapped[float | None] = mapped_column(Float, nullable=True)
    # The id assigned by the Day 1 API, proving the document really landed.
    api_document_id: Mapped[int | None] = mapped_column(Integer, nullable=True)

    fetched_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, nullable=False
    )


class RequestLog(Base):
    """One row per outbound HTTP request. The rate limiter's source of truth.

    WHY A TABLE AND NOT AN IN-MEMORY COUNTER. An in-process dict resets every
    time the container restarts, so `docker compose restart` would silently
    reset an exhausted daily budget and let the crawler hammer a site that
    had already refused it. Persisting means the limit survives restarts,
    and means several processes (the CLI and the UI both crawl) share one
    budget instead of each keeping its own.
    """

    __tablename__ = "request_log"

    __table_args__ = (
        # Every limit query is "count rows for this host since time T", so
        # this composite index is the one that keeps the check O(log n).
        Index("ix_request_log_host_time", "host", "requested_at"),
        # The global limits query by time alone.
        Index("ix_request_log_time", "requested_at"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    host: Mapped[str] = mapped_column(String(255), nullable=False)
    requested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=_utcnow, nullable=False
    )
