"""create documents table

Revision ID: 0001
Revises:
Create Date: 2026-07-27

Hand-written (not autogenerated) so the downgrade is exact and reviewable.
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        # Named explicitly so downgrade can drop it by name and so the app's
        # UniqueConstraint(name="uq_documents_url") matches the real object.
        sa.UniqueConstraint("url", name="uq_documents_url"),
    )
    # Index on source: the list endpoint filters by source, so this keeps
    # GET /documents?source=... fast as the table grows.
    op.create_index("ix_documents_source", "documents", ["source"])


def downgrade() -> None:
    # Exact inverse of upgrade, in reverse dependency order: drop the index
    # first (it depends on the table), then the table. Dropping the table also
    # drops uq_documents_url, so we don't drop the constraint separately.
    # Result: `alembic downgrade base` returns the DB to an empty schema.
    op.drop_index("ix_documents_source", table_name="documents")
    op.drop_table("documents")
