"""add published_at to documents

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-30

WHY THIS COLUMN EXISTS (the question a reviewer will ask, since the table
already has created_at):

    created_at   = when WE stored the row.   Set by us, at insert. Never null.
    published_at = when the AUTHOR published. Read off the page. Often null.

They answer different questions and neither substitutes for the other. The
Day 3 crawler is graded partly on "% of articles with a missing or unparseable
publish date" -- a number that is only meaningful for a date we had to dig out
of someone else's HTML. created_at can never be missing or unparseable because
we generate it, so measuring it would report 0% by construction.

Hand-written (not autogenerated) so the downgrade is exact and reviewable.
"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NULLABLE is the honest type, and it is also what makes this migration
    # safe to run on a table that already has rows. Two reasons:
    #
    #   1. Semantics: NULL means "we looked and could not find a publish date".
    #      That is a real, distinct state from "published at midnight" -- and
    #      it is precisely the state the data-quality report counts. A NOT NULL
    #      column would force us to invent a value and destroy that signal.
    #   2. Safety: adding a NOT NULL column to a populated table requires a
    #      backfill or a server_default. Day 1 rows predate the crawler and
    #      have no true publish date, so any default we picked would be a lie.
    #
    # timezone=True -> TIMESTAMPTZ, matching created_at. Publish dates are
    # scraped from many sites in many zones; we normalise to UTC on the way in,
    # and a timezone-aware column keeps that explicit rather than storing a
    # naive timestamp whose zone you have to guess.
    op.add_column(
        "documents",
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    # Exact inverse. Dropping the column is lossy for the data it held, but
    # that is what a downgrade means here: revision 0001 had no such column,
    # so returning to 0001 must leave the table as 0001 defined it.
    op.drop_column("documents", "published_at")
